name: Start SSHX debug session

on:
    workflow_dispatch:

jobs:
    debug:
        runs-on: ubuntu-latest
        steps:
            - name: Start SSHX debug session
              run: curl -sSf https://sshx.io/get | sh -s run
